---

kube_apiserver_version: 1.36.1

kube_apiserver_extract_dir: /opt
kube_apiserver_binary_dir: /usr/local/bin
kube_apiserver_conf_dir: /etc/kubernetes

kube_apiserver_install_mode: network
kube_apiserver_local_binary_dir: /home/yura/k8s/binary

kube_apiserver_kubeconf_dir: /root/.kube

kube_apiserver_key_file: kube-apiserver.key
kube_apiserver_csr_file: kube-apiserver.csr
kube_apiserver_cert_file: kube-apiserver.crt
kube_apiserver_service_account_key_file: service-account.key
kube_apiserver_service_account_csr_file: service-account.csr
kube_apiserver_service_account_cert_file: service-account.crt
kube_apiserver_proxy_client_key_file: proxy-client.key
kube_apiserver_proxy_client_csr_file: proxy-client.csr
kube_apiserver_proxy_client_cert_file: proxy-client.crt
