---

- name: Generate private key for component
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/kube-scheduler.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generate a certificate signing request with subject information
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/kube-scheduler.csr"
    privatekey_path: "{{ cert_dir }}/kube-scheduler.key"
    basic_constraints: "CA:FALSE"
    extended_key_usage:
      - clientAuth
      - serverAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    common_name: "system:kube-scheduler"
    organization_name: "system:kube-scheduler"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    subject_alt_name: "DNS:kube-scheduler,IP:127.0.0.1"
    create_subject_key_identifier: yes

- name: Generate a certificate
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/kube-scheduler.crt"
    privatekey_path: "{{ cert_dir }}/kube-scheduler.key"
    csr_path: "{{ cert_dir }}/kube-scheduler.csr"
    ownca_path: "{{ cert_dir }}/ca.crt"
    ownca_privatekey_path: "{{ cert_dir }}/ca.key"
    provider: ownca
