---

- name: Ganerate config for services (set cluster)
  ansible.builtin.command: >
    kubectl config set-cluster k8s
    --certificate-authority={{ cert_dir }}/ca.crt
    --embed-certs=true
    --server=https://{{ inventory_hostname }}.{{ domain_name }}:6443
    --kubeconfig={{ kube_scheduler_kubeconfig_dir }}/kube-scheduler.kubeconfig

- name: Ganerate config for services (set credentials)
  ansible.builtin.command: >
    kubectl config set-credentials system:kube-scheduler
    --client-certificate={{ cert_dir }}/kube-scheduler.crt
    --client-key={{ cert_dir }}/kube-scheduler.key
    --embed-certs=true
    --kubeconfig={{ kube_scheduler_kubeconfig_dir }}/kube-scheduler.kubeconfig

- name: Ganerate config for services (set context)
  ansible.builtin.command: >
    kubectl config set-context default
    --cluster=k8s
    --user=system:kube-scheduler
    --kubeconfig={{ kube_scheduler_kubeconfig_dir }}/kube-scheduler.kubeconfig

- name: Set default context for services config
  ansible.builtin.command: >
    kubectl config use-context default
    --kubeconfig={{ kube_scheduler_kubeconfig_dir }}/kube-scheduler.kubeconfig
