---

- name: Generate kubeconfig for kube-sscheduler
  ansible.builtin.template:
    src: kube-scheduler.kubeconfig.j2
    dest: "{{ kube_scheduler_kubeconfig_dir }}/kube-scheduler.kubeconfig"
    mode: '0600'

- name: Flush handlers to restart kube-scheduler immediately
  ansible.builtin.meta: flush_handlers

- name: Verify kubeconfig connectivity after restart
  ansible.builtin.command: kubectl version \ --kubeconfig={{ kube_scheduler_kubeconfig_dir }}/kube-scheduler.kubeconfig
  register: kubeconfig_check
  changed_when: false
  failed_when: kubeconfig_check.rc != 0
