---

- name: Install service kube-scheduler
  ansible.builtin.template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    mode: 0644
  notify:
    - reload systemd

- name: Enable and start kube-scheduler
  ansible.builtin.systemd:
    name: kube-scheduler
    state: started
    enabled: yes

- name: Check started service
  ansible.builtin.service:
    name: kube-scheduler
    state: started
  register: kube_scheduler_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kube-scheduler service is not running. Playbook has stoped."
  when: kube_scheduler_service_status.state != 'started'
