---

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Fix /etc/hosts removing the old hostname
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1\t{{ inventory_hostname }} {{ inventory_hostname }}.{{ domain_name }}"
    state: present

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_host }}$"
    line: "{{ hostvars[item].ansible_host }}\t{{ hostvars[item].inventory_hostname }} {{ item }}.{{ domain_name }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
