---

- name: Preset
  hosts:
    - admin
    - lb
    - master
    - worker
  roles:
    - preset
  tags: preset

- name: Generation ca certificate
  hosts: localhost
  roles:
    - ca_certificate
  become: false
  tags: ca_certificate

- name: Installation kubectl
  hosts:
    - admin
    - master
    - worker
  roles:
    - kubectl
  tags: kubectl

- name: Installation etcd
  hosts: etcd
  roles:
    - etcd
  tags: etcd

- name: Installation kube-apiserver
  hosts:
    - master
  roles:
    - kube_apiserver
  tags: kube-apiserver

- name: Installation haproxy
  hosts:
    - lb
  roles:
    - haproxy
  tags: haproxy

- name: Installation keepalived
  hosts:
    - lb
  roles:
    - keepalived
  tags: keepalived

- name: Installation kube-scheduler
  hosts:
    - master
  roles:
    - kube_scheduler
  tags: kube-scheduler

- name: Installation kube-controller-manager
  hosts:
    - master
  roles:
    - kube_controller_manager
  tags: kube-controller-manager

- name: Installation crictl
  hosts:
    - worker
  roles:
    - crictl
  tags: crictl

- name: Installation runc
  hosts:
    - worker
  roles:
    - runc
  tags: runc

- name: Installation containerd
  hosts:
    - worker
  roles:
    - containerd
  tags: containerd

- name: Installation kubelet
  hosts:
    - worker
  roles:
    - kubelet
  tags: kubelet

- name: Installation cilium
  hosts:
    - localhost
  roles:
    - cilium
  tags: cilium

- name: Installation DNS
  hosts:
    - localhost
  roles:
    - dns
  tags: dns

- name: Installation metrics
  hosts:
    - localhost
  roles:
    - metrics
  tags: metrics
