---

- name: preset
  hosts:
    - admin
    - lb
    - master
    - worker
  roles:
    - os_preset
  tags: preset

- name: ca_certificate
  hosts: localhost
  roles:
    - os_ca_certificate
  become: false
  tags: ca_certificate

- name: kubectl
  hosts:
    - admin
    - master
    - worker
  roles:
    - os_kubectl
  tags: kubectl

- name: etcd
  hosts: etcd
  roles:
    - os_etcd
  tags: etcd

- name: kube_apiserver
  hosts:
    - master
  roles:
    - os_kube_apiserver
  tags: kube-apiserver

- name: haproxy
  hosts:
    - lb
  roles:
    - os_haproxy
  tags: haproxy

- name: keepalived
  hosts:
    - lb
  roles:
    - os_keepalived
  tags: keepalived

- name: kube_scheduler
  hosts:
    - master
  roles:
    - os_kube_scheduler
  tags: kube-scheduler

- name: kube_controller_manager
  hosts:
    - master
  roles:
    - os_kube_controller_manager
  tags: kube-controller-manager

- name: crictl
  hosts:
    - worker
  roles:
    - os_crictl
  tags: crictl

#- name: cni
#  hosts:
#    - master
#    - worker
#  roles:
#    - cni
#  tags: cni

#- name: pod_route
#  hosts:
#    - worker
#  roles:
#    - pod_route
#  tags: pod_route

- name: runc
  hosts:
    - worker
  roles:
    - os_runc
  tags: runc

#- name: kube_proxy
#  hosts:
#    - worker
#  roles:
#    - kube_proxy
#  tags: kube-proxy

- name: containerd
  hosts:
    - worker
  roles:
    - os_containerd
  tags: containerd

- name: kubelet
  hosts:
    - worker
  roles:
    - os_kubelet
  tags: kubelet

- name: dns
  hosts:
    - localhost
  roles:
    - k8s_dns
  tags: dns

- name: cilium
  hosts:
    - localhost
  roles:
    - k8s_cilium
  tags: cilium
