---

# Metrics Server версия
k8s_metrics_version: "0.7.1"

# Ресурсы
k8s_metrics_cpu_request: "100m"
k8s_metrics_cpu_limit: "500m"
k8s_metrics_memory_request: "200Mi"
k8s_metrics_memory_limit: "500Mi"

# Реплики
k8s_metrics_replicas: 1

# Настройки сбора метрик
k8s_metrics_resolution: "15s"
k8s_metrics_metric_duration: "5m0s"
k8s_metrics_kubelet_insecure_tls: true
k8s_metrics_kubelet_preferred_address_types: "InternalIP,Hostname,ExternalIP"

# Нода для размещения (опционально)
k8s_metrics_node_selector: {}
k8s_metrics_tolerations: []

# Автомасштабирование (HPA/VPA требуют metrics-server)
k8s_metrics_enable_autoscaling: true
