---

- name: Add repository Cilium
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
    state: present

- name: Create namespace for Cilium
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ k8s_cilium_namespace }}"
    state: present
  when: cilium_namespace != "kube-system"

- name: Install/update Cilium
  kubernetes.core.helm:
    name: "{{ k8s_cilium_release_name }}"
    chart_ref: cilium/cilium
    chart_version: "{{ k8s_cilium_version }}"
    release_namespace: "{{ k8s_cilium_namespace }}"
    create_namespace: false
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
    values:
      kubeProxyReplacement: "{{ k8s_cilium_kube_proxy_replacement }}"
      k8sServiceHost: "{{ k8s_cilium_service_host }}"
      k8sServicePort: "{{ k8s_cilium_service_port }}"
      routingMode: "{{ k8s_cilium_routing_mode }}"
      tunnelProtocol: "{{ k8s_cilium_tunnel_protocol }}"
      ipam:
        mode: "{{ k8s_cilium_ipam_mode }}"
      autoDirectNodeRoutes: "{{ k8s_cilium_auto_direct_node_routes }}"
      bpf:
        masquerade: "{{ k8s_cilium_bpf_masquerade }}"
      hubble:
        relay:
          enabled: "{{ k8s_cilium_enable_hubble }}"
        ui:
          enabled: "{{ k8s_cilium_enable_hubble_ui }}"
      bandwidthManager:
        enabled: "{{ k8s_cilium_bandwidth_manager }}"
    wait: true
    timeout: 5m

- name: Install cilium-cli for test
  block:
    - name: Скачать бинарник cilium
      get_url:
        url: "https://github.com/cilium/cilium-cli/releases/download/{{ k8s_cilium_cli_version }}/cilium-linux-amd64.tar.gz"
        dest: /tmp/cilium.tar.gz
    - name: Распаковать
      unarchive:
        src: /tmp/cilium.tar.gz
        dest: /usr/local/bin
        remote_src: true
        creates: /usr/local/bin/cilium
  when: install_cilium_cli | default(false) | bool

- name: Waiting ready all pods Cilium
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ k8s_cilium_namespace }}"
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
    label_selectors:
      - "k8s-app=cilium"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
