all:
  children:
    admin:
      hosts:
        admin:
          ansible_host: 192.168.88.40
    master:
      hosts:
        master1:
          ansible_host: 192.168.88.41
        master2:
          ansible_host: 192.168.88.42
        master3:
          ansible_host: 192.168.88.43
    worker:
      hosts:
        worker1:
          ansible_host: 192.168.88.44
          pod_subnet: 192.168.1.0/24
        worker2:
          ansible_host: 192.168.88.45
          pod_subnet: 192.168.2.0/24
