---

kubelet_version: 1.36.1
kubelet_extract_dir: /opt
kubelet_binary_dir: /usr/local/bin
kubelet_config_dir: /var/lib/kubelet

kubelet_install_mode: network
kubelet_local_binary_dir: /home/yura/k8s/binary

kubelet_kubeconfig_dir: /etc/kubernetes

kubelet_resolv_conf: /etc/resolv.conf

kubelet_key_file: kubelet.key
kubelet_csr_file: kubelet.csr
kubelet_cert_file: kubelet.crt
