---

- name: Ganerate config for worker node  (set cluster)
  ansible.builtin.command: >
    kubectl config set-cluster k8s
    --certificate-authority={{ cert_dir }}/{{ ca_cert_file }}
    --embed-certs=true
    --server=https://{{ vip }}:6443
    --kubeconfig={{ kubelet_kubeconfig_dir }}/kubelet.kubeconfig

- name: Ganerate config for worker node (set credentials)
  ansible.builtin.command: >
    kubectl config set-credentials system:node:{{ inventory_hostname }}
    --client-certificate={{ cert_dir }}/{{ kubelet_cert_file }}
    --client-key={{ cert_dir }}/{{ kubelet_key_file }}
    --embed-certs=true
    --kubeconfig={{ kubelet_kubeconfig_dir }}/kubelet.kubeconfig

- name: Ganerate config for worker node (set context)
  ansible.builtin.command: >
    kubectl config set-context default
    --cluster=k8s
    --user=system:node:{{ inventory_hostname }}
    --kubeconfig={{ kubelet_kubeconfig_dir }}/kubelet.kubeconfig

- name: Set default context for services config
  ansible.builtin.command: >
    kubectl config use-context default
    --kubeconfig={{ kubelet_kubeconfig_dir }}/kubelet.kubeconfig
