---

- name: Generate certificate
  ansible.builtin.include_tasks:
    file: cert.yaml

- name: Install and configure kubelet
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Set up kubeconfig file
  ansible.builtin.include_tasks:
    file: kubeconfig.yaml

- name: Set up service kubelet
  ansible.builtin.include_tasks:
    file: service.yaml
