---

- name: Install service kubelet
  ansible.builtin.template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - reload systemd

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes

- name: Check started service
  ansible.builtin.service:
    name: kubelet
    state: started
  register: kubelet_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kubelet service is not running. Playbook has stoped."
  when: kubelet_service_status.state != 'started'
