---

- name: Is kube-controller_manager installed
  ansible.builtin.stat:
    path: "{{ kube_controller_manager_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}/kube-controller-manager"
  register: kube_controller_manager_file_found

- block:

  - name: Create controller-manager directory
    ansible.builtin.file:
      path: "{{ kube_controller_manager_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}"
      state: directory

  - shell: uname -s
    register: os

  - shell: dpkg --print-architecture
    register: architecture

  - name: Download controller-manager from url
    ansible.builtin.get_url:
      url: "https://dl.k8s.io/v{{ kube_controller_manager_version }}/bin/{{ os.stdout | lower }}/{{ architecture.stdout }}/kube-controller-manager"
      dest: "{{ kube_controller_manager_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}"
    when:
      - kube_controller_manager_install_mode == 'network'

  - name: Download etcd from local dir
    ansible.builtin.copy:
      src: "{{ kube_controller_manager_local_binary_dir }}/kube-controller-manager"
      dest: "{{ kube_controller_manager_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}"
    when:
      - kube_controller_manager_install_mode == 'local'

  - name: Create symlinks to /usr/local/bin
    ansible.builtin.file:
      src: "{{ kube_controller_manager_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}/kube-controller-manager"
      path: "{{ kube_controller_manager_binary_dir }}/kube-controller-manager"
      state: link
      mode: a+x

  when:
    - not kube_controller_manager_file_found.stat.exists
