---

- name: Generate kubeconfig for kube-controller-manager
  ansible.builtin.template:
    src: kube-controller-manager.kubeconfig.j2
    dest: "{{ kube_controller_manager_kubeconfig_dir }}/kube-controller-manager.kubeconfig"
    mode: '0600'

- name: Flush handlers to restart kube-controller-manager immediately
  ansible.builtin.meta: flush_handlers

- name: Verify kubeconfig connectivity after restart
  ansible.builtin.command: kubectl version \ --kubeconfig={{ kube_controller_manager_kubeconfig_dir }}/kube-controller-manager.kubeconfig
  register: kubeconfig_check
  changed_when: false
  failed_when: kubeconfig_check.rc != 0
