---

- name: Ganerate config for services (set cluster)
  ansible.builtin.command: >
    kubectl config set-cluster k8s
    --certificate-authority={{ kube_controller_manager_cert_dir }}/{{ ca_cert_file }}
    --embed-certs=true
    --server=https://k8s-master.{{ domain_name }}:6443
    --kubeconfig={{ kube_controller_manager_kubeconf_dir }}/kube-controller-manager.kubeconfig

- name: Ganerate config for services (set credentials)
  ansible.builtin.command: >
    kubectl config set-credentials system:kube-controller-manager
    --client-certificate={{ kube_controller_manager_cert_dir }}/{{ kube_controller_manager_cert_file }}
    --client-key={{ kube_controller_manager_cert_dir }}/{{ kube_controller_manager_cert_key_file }}
    --embed-certs=true
    --kubeconfig={{ kube_controller_manager_kubeconf_dir }}/kube-controller-manager.kubeconfig

- name: Ganerate config for services (set context)
  ansible.builtin.command: >
    kubectl config set-context default
    --cluster=k8s
    --user=system:kube-controller-manager
    --kubeconfig={{ kube_controller_manager_kubeconf_dir }}/kube-controller-manager.kubeconfig

- name: Set default context for services config
  ansible.builtin.command: >
    kubectl config use-context default
    --kubeconfig={{ kube_controller_manager_kubeconf_dir }}/kube-controller-manager.kubeconfig
