---

- name: Configure Kubernetes cluster in kubeconfig for kube-controller-manager
  kubernetes.core.k8s_config:
    kubeconfig: "{{ kube_controller_manager_kubeconfig_dir }}/kube-controller-manager.kubeconfig"
    cluster_name: k8s
    server: "https://{{ fqdn }}:6443"
    certificate_authority: "{{ cert_dir }}/{{ ca_cert_file }}"
    embed_certs: true
    state: present # Указывает, что кластер должен существовать

- name: Configure Kubernetes credentials in kubeconfig for kube-controller-manager
  kubernetes.core.k8s_config:
    kubeconfig: "{{ kube_controller_manager_kubeconfig_dir }}/kube-controller-manager.kubeconfig"
    user_name: "system:kube-controller-manager"
    client_certificate: "{{ cert_dir }}/{{ kube_controller_manager_cert_file }}"
    client_key: "{{ cert_dir }}/{{ kube_controller_manager_key_file }}"
    embed_certs: true
    state: present # Указывает, что учетные данные должны существовать

- name: Configure Kubernetes context in kubeconfig for kube-controller-manager
  kubernetes.core.k8s_config:
    kubeconfig: "{{ kube_controller_manager_kubeconfig_dir }}/kube-controller-manager.kubeconfig"
    context_name: default
    cluster_name: k8s
    user_name: "system:kube-controller-manager"
    state: present # Указывает, что контекст должен существовать

- name: Set default context in kubeconfig for kube-controller-manager
  kubernetes.core.k8s_config:
    kubeconfig: "{{ kube_controller_manager_kubeconfig_dir }}/kube-controller-manager.kubeconfig"
    context_name: default
    state: use_context
