---

- name: Install service kube-controller-manager
  ansible.builtin.template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    mode: 0644
  notify:
    - reload systemd

- name: Enable and start kube-controller-manager
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: started
    enabled: yes

- name: Check started service
  ansible.builtin.service:
    name: kube-apiserver
    state: started
  register: kube_controller_manager_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kube-controller-manager service is not running. Playbook has stoped."
  when: kube_controller_manager_service_status.state != 'started'
