---

keepalived_version: 2.3.4
keepalived_binary_dir: /usr/sbin
keepalived_config_dir: /usr/etc/keepalived
keepalived_script_dir: /usr/lib/keepalived

keepalived_install_mode: network
keepalived_local_archive_dir: /home/yura/k8s/binary

keepalived_auth_pass: "qwerty"
