---

cilium_version: "1.19.4"
cilium_namespace: kube-system
cilium_release_name: cilium

# Параметры установки
cilium_kube_proxy_replacement: true
cilium_routing_mode: "tunnel"
cilium_tunnel_protocol: "geneve"
cilium_service_host: "{{ vip }}"
cilium_service_port: 6443
cilium_ipam_mode: kubernetes
cilium_auto_direct_node_routes: false
cilium_bpf_masquerade: true
cilium_enable_hubble: true
cilium_enable_hubble_ui: true
cilium_bandwidth_manager: false

# Для проверок
cilium_cli_version: "v0.15.23"
