---

k8s_cilium_version: "1.19.4"
k8s_cilium_namespace: kube-system
k8s_cilium_release_name: cilium

# Параметры установки
k8s_cilium_kube_proxy_replacement: true
k8s_cilium_routing_mode: "tunnel"
k8s_cilium_tunnel_protocol: "geneve"
k8s_cilium_service_host: "{{ vip }}"
k8s_cilium_service_port: 6443
k8s_cilium_ipam_mode: kubernetes
k8s_cilium_auto_direct_node_routes: false
k8s_cilium_bpf_masquerade: true
k8s_cilium_enable_hubble: true
k8s_cilium_enable_hubble_ui: true
k8s_cilium_bandwidth_manager: false

# Для проверок
k8s_cilium_cli_version: "v0.15.23"
