---

- block:

  - name: Ganerate kubeconfig admin (set cluster)
    ansible.builtin.command: >
      kubectl config set-cluster k8s
      --certificate-authority={{ cert_dir }}/ca.crt
      --embed-certs=true
      --server=https://k8s-master.local:6443

  - name: Ganerate kubeconfig admin (set credentials)
    ansible.builtin.command: >
      kubectl config set-credentials admin
      --client-certificate={{ cert_dir }}/admin.crt
      --client-key={{ cert_dir }}/admin.key

  - name: Ganerate kubeconfig admin (set context)
    ansible.builtin.command: >
      kubectl config set-context k8s
      --cluster=k8s
      --user=admin

  - name: Choosing the context for use
    ansible.builtin.command: >
      kubectl config use-context k8s

  when:
    - "'admin' in group_names"
