---

- block:

  - name: Ganerate kubeconfig admin (set cluster)
    ansible.builtin.command: >
      kubectl config set-cluster k8s
      --certificate-authority={{ kubectl_cert_dir }}/{{ ca_cert_file }}
      --embed-certs=true
      --server=https://k8s-master.local:6443

  - name: Ganerate kubeconfig admin (set credentials)
    ansible.builtin.command: >
      kubectl config set-credentials admin
      --client-certificate={{ kubectl_cert_dir }}/{{ kubectl_admin_cert_file }}
      --client-key={{ kubectl_cert_dir }}/{{ kubectl_admin_cert_key_file }}

  - name: Ganerate kubeconfig admin (set context)
    ansible.builtin.command: >
      kubectl config set-context k8s
      --cluster=k8s
      --user=admin

  - name: Choosing the context for use
    ansible.builtin.command: >
      kubectl config use-context k8s

  when:
    - "'admin' in group_names"
