---

- name: Generate certificate
  ansible.builtin.include_tasks:
    file: cert.yaml

- name: Install and configure kubectl
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Set up kubeconfig file
  ansible.builtin.include_tasks:
    file: kubeconfig.yaml
