---

- name: Check for existence of CA file
  stat:
    path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
  register: ca_file_status
  delegate_to: localhost
  run_once: true
  become: false

- name: Stop playbook if file does not exist
  fail:
    msg: "file {{ cert_local_dir }}/{{ ca_cert_file }} does not exist."
  when: not ca_file_status.stat.exists
  delegate_to: localhost
  run_once: true
  become: false

- name: Create local directory for etcd certificates
  ansible.builtin.file:
    path: "{{ cert_local_dir }}/etcd"
    state: directory
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate san value
  ansible.builtin.set_fact:
    san: "{{ san_dns + san_ips + san_local_host }}"
  vars:
    san_local_host: ['DNS:localhost', 'IP:127.0.0.1']
    san_dns: "{{ etcd_dns | map('regex_replace', '^', 'DNS:') | map('regex_replace', '$', '.' + cluster_name + '.' + domain_name) | list }}"
    san_ips: "{{ etcd_ips | map('regex_replace', '^', 'IP:') | list }}"

###############################################################################
# Create a etcd server certificate
###############################################################################

- name: Generate private key for etcd
  community.crypto.openssl_privatekey:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_server_key_file }}"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate CSR for server certificate
  community.crypto.openssl_csr:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_server_csr_file }}"
    privatekey_path: "{{ cert_local_dir }}/etcd/{{ etcd_server_key_file }}"
    basic_constraints_critical: true
    basic_constraints: "CA:FALSE"
    extended_key_usage_critical: true
    extended_key_usage:
      - "clientAuth"
      - "serverAuth"
    key_usage_critical: true
    key_usage:
      - "digitalSignature"
      - "keyEncipherment"
    common_name: "system:etcd-server"
    organization_name: "system:etcd-server"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    subject_alt_name: "{{ san }}"
    create_subject_key_identifier: true
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a certificate
  community.crypto.x509_certificate:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_server_cert_file }}"
    privatekey_path: "{{ cert_local_dir }}/etcd/{{ etcd_server_key_file }}"
    csr_path: "{{ cert_local_dir }}/etcd/{{ etcd_server_csr_file }}"
    ownca_path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
    ownca_privatekey_path: "{{ cert_local_dir }}/{{ ca_key_file }}"
    provider: ownca
    ownca_not_after: "+{{ cert_expiry_days }}d"
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

#################################################
# Create a peer certificate
#################################################

- name: Generate private key for etcd peer communication
  community.crypto.openssl_privatekey:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_peer_key_file }}"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate CSR for peer certificate
  community.crypto.openssl_csr:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_peer_csr_file }}"
    privatekey_path: "{{ cert_local_dir }}/etcd/{{ etcd_peer_key_file }}"
    basic_constraints_critical: true
    basic_constraints: "CA:FALSE"
    extended_key_usage_critical: true
    extended_key_usage:
      - "clientAuth"
      - "serverAuth"
    key_usage_critical: true
    key_usage:
      - "digitalSignature"
      - "keyEncipherment"
    common_name: "system:etcd-peer"
    organization_name: "system:etcd-peer"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    subject_alt_name: "{{ san }}"
    create_subject_key_identifier: true
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a certificate
  community.crypto.x509_certificate:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_peer_cert_file }}"
    privatekey_path: "{{ cert_local_dir }}/etcd/{{ etcd_peer_key_file }}"
    csr_path: "{{ cert_local_dir }}/etcd/{{ etcd_peer_csr_file }}"
    ownca_path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
    ownca_privatekey_path: "{{ cert_local_dir }}/{{ ca_key_file }}"
    provider: ownca
    ownca_not_after: "+{{ cert_expiry_days }}d"
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

###############################################################################
# Create a etcd client certificate
###############################################################################

- name: Generate private key for etcd client certificate
  community.crypto.openssl_privatekey:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_client_key_file }}"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate CSR for etcd client certificate
  community.crypto.openssl_csr:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_client_csr_file }}"
    privatekey_path: "{{ cert_local_dir }}/etcd/{{ etcd_client_key_file }}"
    basic_constraints_critical: true
    basic_constraints: "CA:FALSE"
    extended_key_usage_critical: true
    extended_key_usage:
      - "clientAuth"
      - "serverAuth"
    key_usage_critical: true
    key_usage:
      - "digitalSignature"
      - "keyEncipherment"
    common_name: "system:etcd-client"
    organization_name: "system:etcd-client"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    subject_alt_name: "{{ san }}"
    create_subject_key_identifier: true
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a certificate
  community.crypto.x509_certificate:
    path: "{{ cert_local_dir }}/etcd/{{ etcd_client_cert_file }}"
    privatekey_path: "{{ cert_local_dir }}/etcd/{{ etcd_client_key_file }}"
    csr_path: "{{ cert_local_dir }}/etcd/{{ etcd_client_csr_file }}"
    ownca_path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
    ownca_privatekey_path: "{{ cert_local_dir }}/{{ ca_key_file }}"
    provider: ownca
    ownca_not_after: "+{{ cert_expiry_days }}d"
  delegate_to: localhost
  run_once: true
  become: false

################################################################################
# Copy CA to remote servers
################################################################################

- name: Copy CA to remote servers
  ansible.builtin.copy:
    src: "{{ cert_local_dir }}/{{ item }}"
    dest: "{{ cert_dir }}/{{ item }}"
    mode: '0600'
  loop:
    - "{{ ca_key_file }}"
    - "{{ ca_cert_file }}"

################################################################################
# Copy etcd certificates to remote servers
################################################################################

- name: Create directory for etcd certificates
  ansible.builtin.file:
    path: "{{ cert_dir }}/etcd"
    state: directory
    mode: '0700'

- name: Copy certificate to remote servers
  ansible.builtin.copy:
    src: "{{ cert_local_dir }}/etcd/{{ item }}"
    dest: "{{ cert_dir }}/etcd/{{ item }}"
    mode: "{{ '0600' if 'key' in item else '0644' }}" # Ключи - 600, сертификаты - 644
  loop:
    - "{{ etcd_server_key_file }}"
    - "{{ etcd_server_cert_file }}"
    - "{{ etcd_peer_key_file }}"
    - "{{ etcd_peer_cert_file }}"
    - "{{ etcd_client_key_file }}"
    - "{{ etcd_client_cert_file }}"
