---

- name: Generate certificate
  ansible.builtin.include_tasks:
    file: cert.yaml

- name: Install and configure etcd
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Set up service etcd
  ansible.builtin.include_tasks:
    file: service.yaml
