---

- name: Set cluster list
  ansible.builtin.set_fact:
    etcd_cluster_list: "{{ etcd_dns | zip(etcd_ips) | map('join', '=https://') | map('regex_replace', '$', ':2380') | join(',') }}"

- name: Check if etcd is already initialized
  ansible.builtin.stat:
    path: "{{ etcd_data_dir }}/member/snap/db"
  register: etcd_data
  changed_when: false

- name: Install service etcd
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: '0644'
  register: etcd_unit_file
  vars:
    is_initial_run: "{{ not etcd_data.stat.exists }}"
  notify:
    - Reload systemd
    - Restart etcd

- name: Enable etcd service
  ansible.builtin.systemd:
    name: etcd
    enabled: true
    daemon_reload: true
  when: etcd_unit_file.changed

- name: Check started service
  ansible.builtin.service:
    name: etcd
    state: started
  register: etcd_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The etcd service is not running. Playbook has stoped."
  when: etcd_service_status.state != 'started'

- name: Verify etcd cluster health
  ansible.builtin.command: >
    etcdctl --endpoints=https://127.0.0.1:{{ etcd_client_port }} \
      --cacert={{ cert_dir }}/{{ ca_cert_file }} \
      --cert={{ cert_dir }}/etcd/{{ etcd_client_cert_file }} \
      --key={{ cert_dir }}/etcd/{{ etcd_client_key_file }} endpoint health
  register: etcd_health
  changed_when: false

- name: Log etcd health status
  ansible.builtin.debug:
    msg: "The etcd cluster health status: {{ etcd_health }}"
  when: etcd_health.failed
