---

- name: Install service kube-proxy
  ansible.builtin.template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  notify:
    - reload systemd

- name: Enable and start kube-proxy
  ansible.builtin.systemd:
    name: kube-proxy
    state: started
    enabled: yes

- name: Check started service
  ansible.builtin.service:
    name: kube-proxy
    state: started
  register: kube_proxy_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kube-proxy service is not running. Playbook has stoped."
  when: kube_proxy_service_status.state != 'started'
