---

- name: Checking kubectl availability
  ansible.builtin.command: kubectl version --client
  changed_when: false

- name: Apply RBAC for DNS
  ansible.builtin.template:
    src: dns-rbac.yaml.j2
    dest: /tmp/dns-rbac.yaml
    mode: '0644'

- name: Apply RBAC manifest
  ansible.builtin.command: kubectl apply -f /tmp/dns-rbac.yaml --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: true

- name: Deployment DNS
  ansible.builtin.template:
    src: dns-deployment.yaml.j2
    dest: /tmp/dns-deployment.yaml
    mode: '0644'

- name: Apply deployment manifest
  ansible.builtin.command: kubectl apply -f /tmp/dns-deployment.yaml --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: true

- name: Create service for DNS
  ansible.builtin.template:
    src: dns-service.yaml.j2
    dest: /tmp/dns-service.yaml
    mode: '0644'

- name: Apply service manifest
  ansible.builtin.command: kubectl apply -f /tmp/dns-service.yaml --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: true

- name: Waiting for readiness DNS pods
  ansible.builtin.shell: |
    kubectl wait --for=condition=ready pod \
      -l k8s-app=kube-dns \
      -n kube-system \
      --timeout=300s \
      --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: false

- name: Checking DNS operation
  ansible.builtin.shell: |
    kubectl run -n default test-dns \
      --image=busybox:1.36 \
      --restart=Never \
      --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config" \
      --rm -i -- \
      nslookup kubernetes.default.svc.{{ dns_domain }} \
      {{ dns_cluster }}
  changed_when: false
  ignore_errors: true

- name: Deleting temporary manifests
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - coredns-rbac.yaml
    - coredns-deployment.yaml
    - coredns-service.yaml
