---

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ host_name }}"

- name: Fix /etc/hosts removing the old hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1\t{{ host_name }} {{ fqdn }}"
    state: present

- name: Remove existing host string
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_host }}.*$"
    state: absent
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Build hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_host }}$"
    line: "{{ hostvars[item].ansible_host }}\t{{ hostvars[item].inventory_hostname }} {{ item }}.{{ cluster_name }}.{{ domain_name }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
