---

- name: Create Keepalived configuration directory
  ansible.builtin.file:
    path: "{{ keepalived_config_dir }}"
    state: directory

- name: Get interface name
  set_fact:
    interface_name: "{{ ansible_interfaces | select('contains', ansible_default_ipv4.interface) | list | first }}"
  when: ansible_default_ipv4 is defined

- name: Copy file configuration Keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_dir }}/keepalived.conf"
    mode: '0644'
  when: interface_name is defined

- name: Install packages
  ansible.builtin.package:
    name:
      - build-essential
      - libssl-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnl-route-3-dev
      - libnfnetlink-dev
    state: present
    update_cache: true

- name: Download Keepalived from network
  ansible.builtin.get_url:
    url: "https://www.keepalived.org/software//keepalived-{{ keepalived_version }}.tar.gz"
    dest: "/tmp/keepalived-{{ keepalived_version }}.tar.gz"
  when:
    - keepalived_install_mode == 'network'

- name: Download Keepalived from local dir
  ansible.builtin.copy:
    src: "{{ keepalived_local_archive_dir }}/keepalived-{{ keepalived_version }}/"
    dest: "/tmp/keepalived-{{ keepalived_version }}.tar.gz"
  when:
    - keepalived_install_mode == 'local'

- name: Extract Keepalived source
  ansible.builtin.unarchive:
    src: "/tmp/keepalived-{{ keepalived_version }}.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Compile and install Keepalived
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "/tmp/keepalived-{{ keepalived_version }}"
  loop:
    - ./configure --prefix=/usr
    - make
    - make install

- name: Ensure Keepalived scripts directory exists
  ansible.builtin.file:
    path: "{{ keepalived_script_dir }}"
    state: directory
    mode: '0755'

- name: Copy HAProxy check script
  ansible.builtin.template:
    src: haproxy_check.sh.j2
    dest: "{{ keepalived_script_dir }}/haproxy_check.sh"
    mode: '0755'

- name: Enable IP forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
