---

- name: Check for existence of CA file
  stat:
    path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
  register: ca_file_status
  delegate_to: localhost
  run_once: true
  become: false

- name: Stop playbook if file does not exist
  fail:
    msg: "file {{ cert_local_dir }}/{{ ca_cert_file }} does not exist."
  when: not ca_file_status.stat.exists
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate san value
  ansible.builtin.set_fact:
    san: "{{ san_dns + san_ips + san_local_host }}"
  vars:
    san_local_host:
      - "DNS:localhost"
      - "DNS:kubernetes"
      - "DNS:kubernetes.default"
      - "DNS:kubernetes.default.svc"
      - "DNS:kubernetes.default.svc.cluster.local"
      - "DNS:kubernetes.svc.cluster.local"
      - "DNS:api-server.kubernetes.local"
      - "IP:127.0.0.1"
      - "IP:10.32.0.1"
      - "IP:{{ vip }}"
    san_dns: "{{ groups['master'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^', 'DNS:') | map('regex_replace', '$', '.' + cluster_name + '.' + domain_name) | list }}"
    san_ips: "{{ groups['master'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^', 'IP:') | list }}"

################################################################################
# Create a kube-apiserver certificate
################################################################################

- name: Generate private key for kube-apiserver
  community.crypto.openssl_privatekey:
    path: "{{ cert_local_dir }}/{{ kube_apiserver_key_file }}"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate CSR for kube-apiserver certificate
  community.crypto.openssl_csr:
    path: "{{ cert_local_dir }}/{{ kube_apiserver_csr_file }}"
    privatekey_path: "{{ cert_local_dir }}/{{ kube_apiserver_key_file }}"
    basic_constraints_critical: true
    basic_constraints: "CA:FALSE"
    extended_key_usage_critical: true
    extended_key_usage:
      - "clientAuth"
      - "serverAuth"
    key_usage_critical: true
    key_usage:
      - "digitalSignature"
      - "keyEncipherment"
    common_name: "kube-apiserver"
    organization_name: "kube-apiserver"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    subject_alt_name: "{{ san }}"
    create_subject_key_identifier: true
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a kube-apiserver certificate
  community.crypto.x509_certificate:
    path: "{{ cert_local_dir }}/{{ kube_apiserver_cert_file }}"
    privatekey_path: "{{ cert_local_dir }}/{{ kube_apiserver_key_file }}"
    csr_path: "{{ cert_local_dir }}/{{ kube_apiserver_csr_file }}"
    ownca_path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
    ownca_privatekey_path: "{{ cert_local_dir }}/{{ ca_key_file }}"
    provider: ownca
    mode: '0644'
    ownca_not_after: "+{{ cert_expiry_days }}d"
  delegate_to: localhost
  run_once: true
  become: false

################################################################################
# Create a service-account certificate
################################################################################

- name: Generate private key for service-account
  community.crypto.openssl_privatekey:
    path: "{{ cert_local_dir }}/{{ service_account_key_file }}"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a CSR file for service-account
  community.crypto.openssl_csr:
    path: "{{ cert_local_dir }}/{{ service_account_csr_file }}"
    privatekey_path: "{{ cert_local_dir }}/{{ service_account_key_file }}"
    basic_constraints: "CA:FALSE"
    extended_key_usage:
      - clientAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    common_name: "service-account"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    use_common_name_for_san: false
    create_subject_key_identifier: true
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a certificate service-account
  community.crypto.x509_certificate:
    path: "{{ cert_local_dir }}/{{ service_account_cert_file }}"
    privatekey_path: "{{ cert_local_dir }}/{{ service_account_key_file }}"
    csr_path: "{{ cert_local_dir }}/{{ service_account_csr_file }}"
    ownca_path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
    ownca_privatekey_path: "{{ cert_local_dir }}/{{ ca_key_file }}"
    provider: ownca
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

################################################################################
# Create a proxy-client certificate
################################################################################

- name: Generate private key for proxy-client
  community.crypto.openssl_privatekey:
    path: "{{ cert_local_dir }}/{{ proxy_client_key_file }}"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a CSR file for proxy-client
  community.crypto.openssl_csr:
    path: "{{ cert_local_dir }}/{{ proxy_client_csr_file }}"
    privatekey_path: "{{ cert_local_dir }}/{{ proxy_client_key_file }}"
    basic_constraints: "CA:FALSE"
    extended_key_usage:
      - clientAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    common_name: "aggregator"
    organization_name: "system:masters"
    organizational_unit_name: "System"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    use_common_name_for_san: false
    create_subject_key_identifier: true
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

- name: Generate a certificate for proxy-client
  community.crypto.x509_certificate:
    path: "{{ cert_local_dir }}/{{ proxy_client_cert_file }}"
    privatekey_path: "{{ cert_local_dir }}/{{ proxy_client_key_file }}"
    csr_path: "{{ cert_local_dir }}/{{ proxy_client_csr_file }}"
    ownca_path: "{{ cert_local_dir }}/{{ ca_cert_file }}"
    ownca_privatekey_path: "{{ cert_local_dir }}/{{ ca_key_file }}"
    provider: ownca
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

################################################################################
# Copy CA to remote servers
################################################################################

- name: Copy CA to remote servers
  ansible.builtin.copy:
    src: "{{ cert_local_dir }}/{{ item }}"
    dest: "{{ cert_dir }}/{{ item }}"
    mode: '0644'
  loop:
    - "{{ ca_key_file }}"
    - "{{ ca_cert_file }}"

################################################################################
# Copy etcd certificates to remote servers
################################################################################

- name: Create directory for etcd certificates
  ansible.builtin.file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0750'

- name: Copy certificate to remote servers
  ansible.builtin.copy:
    src: "{{ cert_local_dir }}/{{ item }}"
    dest: "{{ cert_dir }}/{{ item }}"
    mode: '0644'
  loop:
    - "{{ kube_apiserver_key_file }}"
    - "{{ kube_apiserver_cert_file }}"
    - "{{ service_account_key_file }}"
    - "{{ service_account_cert_file }}"
    - "{{ proxy_client_key_file }}"
    - "{{ proxy_client_cert_file }}"
