---

- name: Check for existence of CA file
  stat:
    path: "{{ cert_dir }}/{{ ca_cert_file }}"
  register: ca_file_status

- name: Stop playbook if file does not exist
  fail:
    msg: "file {{ cert_dir }}/{{ ca_cert_file }} does not exist. Playbook stopped."
  when: not ca_file_status.stat.exists

- name: Get list ip-addresses kube-apiserver
  set_fact:
    ip_addresses: "{{ groups['master'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^', 'IP:') | map('to_json') | join(',') }}"

- name: Get list hosts kube-apiserver
  set_fact:
    hosts: "{{ groups['master'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$', 'DNS:\\1.{{ domain_name }}') | map('to_json') | join(',') }}"

#################################################
# Create a kube-apiserver certificate
################################################

- name: Generate private key for kube-apiserver
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}//kube-apiserver.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generate CSR for kube-apiserver certificate
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/kube-apiserver.csr"
    privatekey_path: "{{ cert_dir }}/kube-apiserver.key"
    basic_constraints_critical: yes
    basic_constraints: "CA:FALSE"
    extended_key_usage_critical: yes
    extended_key_usage:
      - "clientAuth"
      - "serverAuth"
    key_usage_critical: yes
    key_usage:
      - "digitalSignature"
      - "keyEncipherment"
    common_name: "kube-apiserver"
    organization_name: "kube-apiserver"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    subject_alt_name: >-
      [
        "IP:127.0.0.1",
        "IP:10.32.0.1",
        {{ ip_addresses }},
        "DNS:kubernetes",
        "DNS:kubernetes.default",
        "DNS:kubernetes.default.svc",
        "DNS:kubernetes.default.svc.cluster",
        "DNS:kubernetes.svc.cluster.local",
        {{ hosts }},
        "DNS:api-server.kubernetes.local"
      ]
    create_subject_key_identifier: yes
  register: kube_apiserver_csr

- name: Generate a kube-apiserver certificate
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/kube-apiserver.crt"
    privatekey_path: "{{ cert_dir }}/kube-apiserver.key"
    csr_path: "{{ cert_dir }}/kube-apiserver.csr"
    ownca_path: "{{ cert_dir }}/{{ ca_cert_file }}"
    ownca_privatekey_path: "{{ cert_dir }}/{{ ca_key_file }}"
    provider: ownca
    ownca_not_after: "+{{ cert_expiry_days }}d"
  when: kube_apiserver_csr is changed

#################################################
# Create a service-account certificate
#################################################

- name: Generate private key for service-account
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/service-account.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generate a certificate signing request with subject information for service-account
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/service-account.csr"
    privatekey_path: "{{ cert_dir }}/service-account.key"
    basic_constraints: "CA:FALSE"
    extended_key_usage:
      - clientAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    common_name: "service-account"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    use_common_name_for_san: false
    create_subject_key_identifier: yes

- name: Generate a certificate service-account
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/service-account.crt"
    privatekey_path: "{{ cert_dir }}/service-account.key"
    csr_path: "{{ cert_dir }}/service-account.csr"
    ownca_path: "{{ cert_dir }}/ca.crt"
    ownca_privatekey_path: "{{ cert_dir }}/ca.key"
    provider: ownca

#################################################
# Create a proxy-client certificate
#################################################

- name: Generate private key for proxy-client
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/proxy-client.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generate a certificate signing request with subject information for proxy-client
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/proxy-client.csr"
    privatekey_path: "{{ cert_dir }}/proxy-client.key"
    basic_constraints: "CA:FALSE"
    extended_key_usage:
      - clientAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    common_name: "aggregator"
    organization_name: "system:masters"
    organizational_unit_name: "System"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    use_common_name_for_san: false
    create_subject_key_identifier: yes

- name: Generate a certificate for proxy-client
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/proxy-client.crt"
    privatekey_path: "{{ cert_dir }}/proxy-client.key"
    csr_path: "{{ cert_dir }}/proxy-client.csr"
    ownca_path: "{{ cert_dir }}/ca.crt"
    ownca_privatekey_path: "{{ cert_dir }}/ca.key"
    provider: ownca
