---

- name: Generate certificate
  ansible.builtin.include_tasks:
    file: cert.yaml

- name: Encription configure file
  ansible.builtin.include_tasks:
    file: encryption_config.yaml

- name: Install and configure kube-apiserver
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Set up service kube-apiserver
  ansible.builtin.include_tasks:
    file: service.yaml

- name: Set up RBCA roles
  ansible.builtin.include_tasks:
    file: rbca_role.yaml
