---

- name: Install service kube-apiserver
  ansible.builtin.template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 0644
  register: service_file_changed

- name: Enable kube-apiserver (only on creation)
  ansible.builtin.systemd:
    name: kube-apiserver
    state: started
    enabled: yes
  when: ansible_service_facts.ansible_facts.services is not defined or ansible_service_facts.ansible_facts.services[service_name] is not defined

- name: Reload systemd daemon and restart service
  ansible.builtin.systemd:
    name: kube-apiserver
    daemon_reload: yes
    state: restarted
  when: service_file_changed.changed
  notify: reload systemd

- name: Check started service
  ansible.builtin.service:
    name: kube-apiserver
    state: started
  register: kube_apiserver_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kube-apiserver service is not running. Playbook has stoped."
  when: kube_apiserver_service_status.state != 'started'
