---

- name: Prepare etcd servers string
  set_fact:
    etcd_servers_string: "{{ groups['etcd'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', 'https://\\1:2379') | join(',') }}"

- name: Install service kube-apiserver
  ansible.builtin.template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 0644
  register: service_file_changed

- name: Enable kube-apiserver (only on creation)
  ansible.builtin.systemd:
    name: kube-apiserver
    state: started
    enabled: true
  when: ansible_service_facts.ansible_facts.services is not defined or ansible_service_facts.ansible_facts.services[service_name] is not defined

- name: Reload systemd daemon and restart service
  ansible.builtin.systemd:
    name: kube-apiserver
    daemon_reload: true
    state: restarted
  when: service_file_changed.changed
  notify: reload systemd

- name: wait kube-apiserver to be ready
  ansible.builtin.uri:
    url: "https://localhost:6443/healthz"
    validate_certs: false
    status_code: 200
  until: apiserver_healthz.status == 200
  retries: 10
  delay: 10
  register: apiserver_healthz

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kube-apiserver service is not running. Playbook has stoped."
  when: apiserver_healthz.status != 200
