---

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart kube-scheduler
  ansible.builtin.systemd:
    name: kube-scheduler
    state: restarted
    enabled: yes
