---

kube_scheduler_version: 1.30.0

kube_scheduler_extract_dir: /opt
kube_scheduler_binary_dir: /usr/local/bin
kube_scheduler_config_dir: /var/lib/kubernetes

kube_scheduler_install_mode: network
kube_scheduler_local_binary_dir: /home/yura/k8s/binary

kube_scheduler_kubeconfig_dir: /etc/kubernetes
