---

- name: Set up hostname
  ansible.builtin.include_tasks:
    file: hostname.yaml

- name: Turning off swap
  ansible.builtin.include_tasks:
    file: swap.yaml

- name: Install packeges
  ansible.builtin.include_tasks:
    file: packages.yaml

- name: Set up sysctl parameters
  ansible.builtin.include_tasks:
    file: sysctl.yaml
