---

- name: Check if swap is active
  ansible.builtin.command: swapon --show
  register: swap_info
  changed_when: false

- name: Disable swap in current session
  ansible.builtin.command: swapoff -a
  when: swap_info.stdout != ""

- name: Disable swap after reboot
  ansible.builtin.replace:
    path: "/etc/fstab"
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
