---

- name: Create file /etc/sysctl.d/k8s.conf
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    create: true
    mode: '0644'
  register: sysctl_config_changed

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  when: sysctl_config_changed.changed
