---

- name: Availability check kubectl
  ansible.builtin.command: kubectl version --client
  changed_when: false

- name: Apply RBAC for metrics server
  ansible.builtin.template:
    src: metrics-rbac.yaml.j2
    dest: /tmp/metrics-rbac.yaml
    mode: '0644'

- name: Apply RBAC manifest
  ansible.builtin.command: |
    kubectl apply -f /tmp/metrics-rbac.yaml \
      --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: true

- name: Deployment metrics server
  ansible.builtin.template:
    src: metrics-deployment.yaml.j2
    dest: /tmp/metrics-deployment.yaml
    mode: '0644'

- name: Apply deployment manifest
  ansible.builtin.command: |
    kubectl apply -f /tmp/metrics-deployment.yaml \
      --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: true

- name: Create APIService for metrics server
  ansible.builtin.template:
    src: metrics-apiservice.yaml.j2
    dest: /tmp/metrics-apiservice.yaml
    mode: '0644'

- name: Apply APIService manifest
  ansible.builtin.command: |
    kubectl apply -f /tmp/metrics-apiservice.yaml \
      --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: true

- name: Waiting for readiness metrics server pod
  ansible.builtin.shell: |
    kubectl wait --for=condition=ready pod \
      -l k8s-app=metrics-server \
      -n kube-system \
      --timeout=400s \
      --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: false

- name: Waiting for readiness API metric
  ansible.builtin.shell: |
    kubectl top nodes \
      --kubeconfig="{{ lookup('env', 'HOME') }}/.kube/config"
  changed_when: false
  register: metrics_test
  ignore_errors: true

- name: Output of the metrics check result
  ansible.builtin.debug:
    msg: "{{ metrics_test.stdout_lines }}"

- name: Deleting temporary manifests
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - metrics-rbac.yaml
    - metrics-deployment.yaml
    - metrics-apiservice.yaml
